spring.datasource.url=jdbc:postgresql://localhost:5432/ipi
spring.datasource.username=intern
spring.datasource.password= DB_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ================================
# IP SEARCH CONFIGURATION
# ================================

# Switch between API and local/static data
ip.api.enabled=false

# External API config (for next milestone)
ip.api.key=d6fc3b3a92083cfb42a99bf1766b1de9ad5102df770e8cee329f78aa829724ab
ip.api.url=https://serpapi.com/search
