spring.datasource.url= ${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}

frontend_url = ${FRONTEND_URL}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ================================
# IP SEARCH CONFIGURATION
# ================================

# Switch between API and local/static data
ip.api.enabled=false

# External API config (for next milestone)
ip.api.key=${IP.API.KEY}
ip.api.url=${IP.API.URL}
