spring.datasource.url=jdbc:postgresql://localhost:5432/ipi
spring.datasource.username=intern
spring.datasource.password= USER_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true